version: '3.8'
services:
  finansys-web:
    image: finansys-web
    container_name: finansys-web
    build: .
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - '8888:80'
    networks:
      - finansys-network
networks:
  finansys-network:
    name: finansys-network
    driver: bridge
